export * from './HomePage/HomePage'
export * from './AboutUsPage/AboutUsPage'
export * from './ServicesPage/ServicesPage'
export * from './StaffPage/StaffPage'
export * from './ValuesPage/ValuesPage'
export * from './WorkPage/WorkPage'
// export * from './PageNotFound/PageNotFound'
// export * from './ProjectDetailPage/ProjectDetailPage'
export * from './ContactUsPage/ContactUsPage'